name: loc_checker

description: A tool to detect non-localized strings in Flutter projects and generate ARB files with camelCase keys.

homepage: https://github.com/alisabry22/full_localization_checker
repository: https://github.com/alisabry22/full_localization_checker
issue_tracker: https://github.com/alisabry22/full_localization_checker/issues
license: MIT
version: 1.0.0

executables:
  loc_checker: loc_checker
environment:
  sdk: ">=2.10.2 <2.11.0"

# Add regular dependencies here.
dependencies:
  args: ^1.6.0
  path: ^1.7.0
  glob: ^1.2.1


  file: ^5.2.1
  analyzer: ^0.41.2

# dev_dependencies:
#   lints: ^5.1.1
#   test: ^1.24.0
  
